doctrine_migrations:
    custom_template: '%kernel.project_dir%/migrations/migration.tpl'
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'LamaMigrations': '%kernel.project_dir%/migrations'
